name: Daily Data Update

on:
  schedule:
    - cron: '1 0 * * *'  # Corre todos los días a las 00:01 (UTC)
  workflow_dispatch:      # Permite ejecutar el workflow manualmente

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build scripts
        run: npm run build:scripts

      - name: Run update script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          COR_API_KEY: ${{ secrets.COR_API_KEY }}
          COR_CLIENT_SECRET: ${{ secrets.COR_CLIENT_SECRET }}
          FACTORIAL_API_KEY: ${{ secrets.FACTORIAL_API_KEY }}
        run: npm run updateData
