name: Actualizar datos y vistas materializadas

on:
  schedule:
    - cron: '1 0 * * *'  # Ejecuta a las 00:01 UTC todos los días
  workflow_dispatch:  # Permite ejecutar manualmente desde la interfaz de GitHub

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install